// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: aws.proto

package aws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializeProviderInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	IamPrefix   string `protobuf:"bytes,2,opt,name=iam_prefix,json=iamPrefix,proto3" json:"iam_prefix,omitempty"`
}

func (x *InitializeProviderInput) Reset() {
	*x = InitializeProviderInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeProviderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeProviderInput) ProtoMessage() {}

func (x *InitializeProviderInput) ProtoReflect() protoreflect.Message {
	mi := &file_aws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeProviderInput.ProtoReflect.Descriptor instead.
func (*InitializeProviderInput) Descriptor() ([]byte, []int) {
	return file_aws_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeProviderInput) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *InitializeProviderInput) GetIamPrefix() string {
	if x != nil {
		return x.IamPrefix
	}
	return ""
}

type InitializeProviderOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeProviderOutput) Reset() {
	*x = InitializeProviderOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeProviderOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeProviderOutput) ProtoMessage() {}

func (x *InitializeProviderOutput) ProtoReflect() protoreflect.Message {
	mi := &file_aws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeProviderOutput.ProtoReflect.Descriptor instead.
func (*InitializeProviderOutput) Descriptor() ([]byte, []int) {
	return file_aws_proto_rawDescGZIP(), []int{1}
}

var File_aws_proto protoreflect.FileDescriptor

var file_aws_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x17, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x61, 0x6d,
	0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x61, 0x6d, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x1a, 0x0a, 0x18, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x32, 0x57, 0x0a, 0x0a, 0x41, 0x57, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x19, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x66,
	0x75, 0x6c, 0x63, 0x6f, 0x2f, 0x6f, 0x61, 0x6b, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aws_proto_rawDescOnce sync.Once
	file_aws_proto_rawDescData = file_aws_proto_rawDesc
)

func file_aws_proto_rawDescGZIP() []byte {
	file_aws_proto_rawDescOnce.Do(func() {
		file_aws_proto_rawDescData = protoimpl.X.CompressGZIP(file_aws_proto_rawDescData)
	})
	return file_aws_proto_rawDescData
}

var file_aws_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aws_proto_goTypes = []interface{}{
	(*InitializeProviderInput)(nil),  // 0: InitializeProviderInput
	(*InitializeProviderOutput)(nil), // 1: InitializeProviderOutput
}
var file_aws_proto_depIdxs = []int32{
	0, // 0: AWSService.InitializeProvider:input_type -> InitializeProviderInput
	1, // 1: AWSService.InitializeProvider:output_type -> InitializeProviderOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aws_proto_init() }
func file_aws_proto_init() {
	if File_aws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeProviderInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeProviderOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aws_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aws_proto_goTypes,
		DependencyIndexes: file_aws_proto_depIdxs,
		MessageInfos:      file_aws_proto_msgTypes,
	}.Build()
	File_aws_proto = out.File
	file_aws_proto_rawDesc = nil
	file_aws_proto_goTypes = nil
	file_aws_proto_depIdxs = nil
}
