// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: aws.proto

package aws

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AWSServiceClient is the client API for AWSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AWSServiceClient interface {
	InitializeProvider(ctx context.Context, in *InitializeProviderInput, opts ...grpc.CallOption) (*InitializeProviderOutput, error)
}

type aWSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAWSServiceClient(cc grpc.ClientConnInterface) AWSServiceClient {
	return &aWSServiceClient{cc}
}

func (c *aWSServiceClient) InitializeProvider(ctx context.Context, in *InitializeProviderInput, opts ...grpc.CallOption) (*InitializeProviderOutput, error) {
	out := new(InitializeProviderOutput)
	err := c.cc.Invoke(ctx, "/AWSService/InitializeProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AWSServiceServer is the server API for AWSService service.
// All implementations must embed UnimplementedAWSServiceServer
// for forward compatibility
type AWSServiceServer interface {
	InitializeProvider(context.Context, *InitializeProviderInput) (*InitializeProviderOutput, error)
	mustEmbedUnimplementedAWSServiceServer()
}

// UnimplementedAWSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAWSServiceServer struct {
}

func (UnimplementedAWSServiceServer) InitializeProvider(context.Context, *InitializeProviderInput) (*InitializeProviderOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeProvider not implemented")
}
func (UnimplementedAWSServiceServer) mustEmbedUnimplementedAWSServiceServer() {}

// UnsafeAWSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AWSServiceServer will
// result in compilation errors.
type UnsafeAWSServiceServer interface {
	mustEmbedUnimplementedAWSServiceServer()
}

func RegisterAWSServiceServer(s grpc.ServiceRegistrar, srv AWSServiceServer) {
	s.RegisterService(&AWSService_ServiceDesc, srv)
}

func _AWSService_InitializeProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeProviderInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSServiceServer).InitializeProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AWSService/InitializeProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSServiceServer).InitializeProvider(ctx, req.(*InitializeProviderInput))
	}
	return interceptor(ctx, in, info, handler)
}

// AWSService_ServiceDesc is the grpc.ServiceDesc for AWSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AWSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AWSService",
	HandlerType: (*AWSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeProvider",
			Handler:    _AWSService_InitializeProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aws.proto",
}
